### PR TITLE
Implement Header (desktop version)

### PR DESCRIPTION
**Pull request by jhoerr**
This PR implements the desktop version of the header. All permutations of Nav and Identity are supported. We will implement the mobile (drawer) variant in a subsequent branch.

### CODE REVIEW

**Comment by jhoerr** [comment]
@athill 
Re `Dropdown.tsx`: This was needed to support proper dropdown alignment when used in the header. 
Re `Footer.tsx`: The header is not rivetized and we modified the footer to match.

**Comment by athill** [comment]
@jhoerr Thanks.

**Comment by jhoerr** [comment]
@athill We maybe should have waited on deleting the `.js` files, but the jump in test coverage was an irresistible endorphine rush at 5 on a Friday. :P

**Comment by athill** [comment]
@jhoerr Ha. Understood. Just like to keep PRs small and focused, but not a big deal.

**Pull request merged**
